### Programming exercise 1:

In [1]:
import numpy as np
from scipy import stats

In [2]:
def hypothesis_test(data, significance_level):
    k2, p = stats.normaltest(data)
    return p

In [3]:
data_1 = np.loadtxt('data1.txt', delimiter='\n')
p = hypothesis_test(data_1,0.05)
if p > significance_level:
    print('Sample looks Gaussian (fail to reject H0)')
else:
    print('Sample does not look Gaussian (reject H0)')

NameError: name 'significance_level' is not defined

In [ ]:
data_2 = np.loadtxt('data2.txt', delimiter='\n')
p = hypothesis_test(data_2,0.05)
if p > significance_level:
    print('Sample looks Gaussian (fail to reject H0)')
else:
    print('Sample does not look Gaussian (reject H0)')

### Programming exercise 2:

In [ ]:
from numpy import random, sqrt, log, sin, cos, pi

# transformation function
def gaussian(n,mu,sigma):
    # uniformly distributed values between 0 and 1
    np.random.seed(28041990)
    u1 = random.uniform(size = n)
    u2 = random.uniform(size = n)
    
    z1= sqrt(-2*log(u1))*cos(2*pi*u2)
    z2 = sqrt(-2*log(u1))*sin(2*pi*u2)
    return z1*sigma + mu, z2*sigma + mu

    

In [ ]:
 random.uniform(size = 10)

In [ ]:
z1,z2 = gaussian(1000,10, 2.5)
x = np.concatenate((z1, z2))
p = hypothesis_test(x)
if p > significance_level:
    print('Sample looks Gaussian (fail to reject H0)')
else:
    print('Sample does not look Gaussian (reject H0)')

In [ ]:
from pylab import show,hist,subplot,figure
import matplotlib.pyplot as plt
from scipy.stats import norm
plt.hist(x, density=True, bins=30, label="Data")
plt.scatter(x, norm.pdf(x,10, 2.5),color= 'red',  label="PDF")
plt.legend(loc="upper left")
plt.show()

### Programming exercise 3:

In [ ]:
import pandas as pd

In [ ]:
iris_data = pd.read_csv("iris_data.csv")

In [ ]:
iris_data.head()

In [ ]:
from sklearn.preprocessing import StandardScaler
features = ['# sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
x = iris_data.loc[:, features].values

In [ ]:
x = StandardScaler().fit_transform(x)


In [ ]:
pd.DataFrame(data = x, columns = features).head()


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2', 'principal component 3'])

In [ ]:
principalDf.head()

In [ ]:
def set_species_name(coulum):
    
    if coulum['species'] == '0.0':
        val = 'setosa'
        print(coulum['species'])
    elif coulum['species'] == 1.0:
        val = 'versicolor'
    else:
        val = 'virginica'
    return val

In [ ]:
finalDf = pd.concat([principalDf, iris_data.iloc[:,-3]], axis = 1)
finalDf = finalDf.rename(columns={'species (0: setosa': 'species'})


In [ ]:
fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(1,1,1) 
ax.set_xlabel('Principal Component 1', fontsize = 15)
ax.set_ylabel('Principal Component 2', fontsize = 15)
ax.set_title('2 Component PCA', fontsize = 20)


species = [0.0, 1.0, 2.0]
colors = ['r', 'g', 'b']
for specie, color in zip(species,colors):
    indicesToKeep = finalDf['species'] == specie
    ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1']
               , finalDf.loc[indicesToKeep, 'principal component 2']
               , c = color
               , s = 50)
ax.legend(['setosa', 'Versicolour','Virginica'])
ax.grid()

In [ ]:
variance = pca.explained_variance_ratio_

In [ ]:
y = finalDf['species'].values
# y = np.int_(y)

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
centers = [[1, 1], [-1, -1], [1, -1]]
fig = plt.figure(1, figsize=(8, 7))
plt.clf()
ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)

plt.cla()

X = principalComponents
for name, label in [('Setosa', 0), ('Versicolour', 1), ('Virginica', 2)]:
    ax.text3D(X[y == label, 0].mean(),
              X[y == label, 1].mean() + 1.5,
              X[y == label, 2].mean(), name,
              horizontalalignment='center',
              bbox=dict(alpha=.5, edgecolor='w', facecolor='w'))
# Reorder the labels to have colors matching the cluster results
# y = np.choose(y, [1, 2, 0]).astype(np.float)
ax.scatter(X[:, 0], X[:, 1], X[:, 2], c=y, cmap=plt.cm.nipy_spectral,
           edgecolor='k')

# ax.w_xaxis.set_ticklabels([])
# ax.w_yaxis.set_ticklabels([])
# ax.w_zaxis.set_ticklabels([])
ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.set_zlabel("PC3")


plt.show()

In [20]:
u = np. random.uniform(siz

In [21]:
u[0]

array([0.15932417])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
success = True

In [16]:
~success

-2

In [18]:
def tuhin():
    print('Hello')

In [19]:
tuhin()

Hello


In [22]:
range(10)

range(0, 10)

In [23]:
xn = np.random.normal(1000)

In [24]:
import matplotlibl

NameError: name 'plt' is not defined

In [33]:
tt = np.zeros((5,4))

In [34]:
tt

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
tt[:,3]

array([0., 0., 0., 0., 0.])

In [40]:
dd = np.array([3,2,6])
dd[1:3]

array([2, 6])