In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
comp1a = np.array([[1,-3,2]]).transpose()
comp1a

array([[ 1],
       [-3],
       [ 2]])

In [3]:
comp2a=np.array([[1,-1]])
comp2a

array([[ 1, -1]])

In [4]:
comp3a = np.array([[1,2,0],[-3,-2,1]])

In [5]:
np.dot(comp2a,comp3a)

array([[ 4,  4, -1]])

In [6]:
expression1a = LA.norm(comp1a, ord=1 )+(np.dot(np.dot(comp2a,comp3a),comp1a))
expression1a

array([[-4.]])

In [7]:
comp1b = np.array([[0,-1,-2]]).transpose()

In [8]:
comp2b = np.array([[1,-3]]).transpose()

In [9]:
comp3b = np.array([[1,-3]])

In [10]:
comp4b = comp3b.transpose()

In [11]:
comp5b = np.array([[1,2]]).transpose()

In [12]:
comp6b = np.array([[1,-2]])

In [13]:
expression1b =(LA.norm(comp1b,ord=np.inf)**2) * ((LA.norm(comp2b)**0.5) * np.dot(comp3b,np.dot(comp4b,np.dot(comp5b,comp6b))))
expression1b

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [ ]:
LA.norm(comp2b)**0.5

In [ ]:
np.dot(comp4b,np.dot(comp3b,np.dot(comp5b,comp6b)))

In [14]:
print(np.finfo(float).eps)


2.220446049250313e-16
